services:
  - type: web
    name: api-dofus
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: USERNAME_MONGODB
        fromDatabase: true
      - key: PASSWORD_MONGODB
        fromDatabase: true
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/api-dofus-449401-0e57d49ea6d3.json
      - key: ALLOWED_ORIGINS
        value: https://dofusquest.app,capacitor://localhost,http://localhost:8100